### ISSUE TITLE
这个qqwry.dat文件可以破解然后我按需求自定义修改不

### ISSUE THREAD

**Issue by maojianyou** [HMBSbige/qqwry#2]
这个qqwry.dat文件可以破解然后我按需求自定义修改不

**Comment by HMBSbige** [comment]
很老的格式了，自行搜索研究吧

**Comment by maojianyou** [comment]
> 很老的格式了，自行搜索研究吧

没找到呢，我是直接调用nali 回显IP归属，但很多不准，想自行定义一个准的IP运营商数据库，这个有啥好的办法不
